### ISSUE TITLE
Setup for PS5 link to a non existant repo

### ISSUE THREAD

**Issue by Firefly74940** [PlayFab/PlayFabMultiplayerUnreal#20]
Hi, 
the setup for ps5 seems to try to clone a repo that is non existant:
https://dev.azure.com/PlayFabPrivate/PS5/_git/PlayFabMultiplayerUnrealPlayStation
i do have access to the PlayFabPartyPS5 repo
The person i contacted at PlayFabSdkAccess@microsoft.com seem to not know about this PlayFabMultiplayerUnrealPlayStation and looks unable to grant me the access 

who can i contact for this matter ?

**Comment by nassosterz-ms** [comment]
Hello,

I have redirected this request to my colleagues, and we will be back shortly with a response.

**Comment by nassosterz-ms** [comment]
Lets drive this conversation over email. Could you send me an email at aterzakis@microsoft.com?

**Comment by PushpadantK** [comment]
Hello, can you include pkacha@micrsoft.com and aterzakis@microsoft.com on the email you have sent to PlayFabSdkAccess@microsoft.com.
We should be able to resolve the access issue from there.

**Comment by Firefly74940** [comment]
Hello @PushpadantK looks like there is a typo in the pkacha email, could you comfirm it ?
