### ISSUE TITLE
Warning creates unnecessary log entries during build and tools.

### ISSUE THREAD

**Issue by bwagstaff** [PlayFab/PlayFabMultiplayerUnreal#23]
This "warning" is unnecessary in many conditions. All the warnings in this function should probably be limited to only when the game itself is running, not the tools nor the editor.

https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/7e146a22a4adf81301a89f367756dc0b7c347a4e/Source/Private/OnlineSubsystemPlayFabModule.cpp#L70

**Comment by PushpadantK** [comment]
Since this is for debuggin and not show up on retail, we will not be updating this part of the code.
