### ISSUE TITLE
Docs show deprecated (even breaking) apis

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/PlayFabMultiplayerUnreal#27]
Your Unreal quickstart guide:

https://learn.microsoft.com/en-us/gaming/playfab/sdks/unreal/quickstart

Demos in the UE4 Quickstart docs use the Client/ API call line, starting with Auth (well -- only Auth. You guys _desperately_ could use more Unreal samples, but I digress).

You can say they are "not deprecated unless marked" all you want, but it's been nearly 2 years and your Client/Matchmaking call from the Unreal SDK (and likely other SDKs) **is 100% broken since the req'd param includes `GameMode` that can no longer be configured**, resulting in infinite "game mode not found" errors. Since you already publicly have replacements under /Multiplayer, this is the definition of deprecating old modules since there's less support for the older ones and they are going away in favor of the newer ones.

1. Update your API docs: Mark either deprecated or obsolete and link to the new one. Obsolete for _at least_ Matchmaking. I only tested 3 Client/ implementations and if 1:3 are obsolete/broken, that's a high probability others are, too.
2. Update your Unreal quickstart guide.
3. Update your sdk inline docs and mark deprecation attributes/macros.

Not even staff seem to be aware of what's going on between v1/v2 and your users are confused. No one seems to even be aware that Client/Matchmake is even broken and has likely been broken for 1.5 years (assuming the majority of your Unreal users have Legacy accounts that can still access the old calls; hence the lack of reports). Since it's been nearly 2 years and at least one of your Apis within your SDK(s) are completely broken and others are "not deprecated but with replacements that have existed for almost 2 years" , I would go as far as calling it negligence, costing your users time, money and confusion.

Folks, please -- _at minimum_, please update all the Client/Matchmaking docs/sdks since they literally do not work anymore unless you have a legacy account.

**Comment by nassosterz-ms** [comment]
Thank you for reporting that, once the doc page is updated we will close this issue!

**Comment by dylanh724** [comment]
> Thank you for reporting that, once the doc page is updated we will close this issue!

Both the Api docs and the Unreal quickstart guide for the online docs - but don't forget the inline docs, too:

(From #3 above) Some people familiar with the schema may not need to look at the docs and only use inline: Please also update the inline SDK docs and mark with the proper deprecated flags.

**Comment by nassosterz-ms** [comment]
I wanted to provide an update, that the team responsible for these APIs / documentation has been informed and is working on fixing these docs. I will keep the issue open until the update occurs and is published.

**Comment by yuehanlin** [comment]
The document has been updated and can be found at https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/matchmaking/quickstart#:~:text=Note,Quickstart%20%2D%20Client%20SDK. Therefore, I'm going to close this thread.
