### ISSUE TITLE
Breaking repo naming consistency

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/PlayFabMultiplayerUnreal#28]
https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart#initial-setup

## Initial setup

> Copy the `OnlineSubsystemPlayFab` (!) folder ...

Expected: `PlayFabMultiplayerUnreal`

Must've been renamed. Not a huge deal, but a small issue in a big chain of relating bigger issues that growingly get more frustrating.

There are already so many inconsistencies between the SDK names, API names, repo names (the Unreal MP SDK **has about 5 names in the docs**, causing your users to endlessly look through your doc link rabbit holes for SDKs where only 1 of 5 _actually exists_), [...]. 

That said, it's probably about time to start cracking down on those -- it only confuses your users. You folks really need a professional UX tech doc writer familiar with PF to go in and just fix these things en masse. That will only bandaid the issues, however, if doc-updating practices remain as sterile as it has been.

**Comment by nassosterz-ms** [comment]
Hello,

Thank you for opening this issue. Could you clarify further what do you mean by:

**Expected: PlayFabMultiplayerUnreal**

Every issue brings valuable feedback to us, so appreciate you taking the time to open this.

**Comment by dylanh724** [comment]
> Hello,
> 
> Thank you for opening this issue. Could you clarify further what do you mean by:
> 
> **Expected: PlayFabMultiplayerUnreal**
> 
> Are you referring to our UE plugin being named PlayFabMultiplayerUnreal to align with the name of this repo?
> 
> Every issue brings valuable feedback to us, so appreciate you taking the time to open this.

Correct - the instructions say to move the dir named OnlineSubsystemPlayFab that does not exist.

**Comment by nassosterz-ms** [comment]
I see.

The instructions indeed point to a stale name, we will update this accordingly!

**Comment by dylanh724** [comment]
> I see.
> 
> The instructions indeed point to a stale name, we will update this accordingly!

Cheers, and please do consider more doc updates! For example, the entire Client/ and Admin/ Apis were deprecated two years ago without even saying anything. Please read the following with a factual tone, as it may seem aggressive but is more so simply saddening due to the experience I've had:

What gets even worse is your Unreal example (the ONLY example, may I add) starts you off wrong immediately down the deprecated Client/ path, forcing me to implement deprecated and even breaking (below) obsolete apis that I now need to recode due to doc negligence.

Client/Matchmaking is even completely obsolete since GameMode cannot be configured in newer accounts without any notice. To make things more confusing, Matchmaker is ALSO obsolete. Why would there even be 2 matchmaking modules and both obsolete?

But wait, there's a third Multiplayer/Matchmaking module that is the correct one... But is completely missing event callbacks that, for some reason, is now in a completey DIFFERENT sdk (unlike the other 2 apis), yet the docs are so scattered it's impossible to know this. That means you have FOUR matchmaking apis, of which 2 are deprecated and 1 completely hidden.

Then that different SDK for matchmaking I mentioned? The docs call it **5 different names**, friend. Multiplayer SDK. Game SDK. Client SDK. Matchmaking SDK. OSS SDK. There's already doubt since there are 4 matchmaking apis and 2 are broken - then had even more doubt if I even had the right one. The OSS SDK or whatever it's called isn't in the API docs, either, so it's just a guessing game from the limited and conflicted info I have.

This experience has been rough. Very rough. Only because documentation and guides are 2 years stale despite the numerous changes within this time.

Please. Add not only tech doc writers, but UX writers. Your users deserve this.

**Comment by dylanh724** [comment]
![image](https://user-images.githubusercontent.com/8840024/216044614-3b2a4a34-2b15-4252-9452-cb7bccbfcf16.png)

On top of that, the old name seems to actually be more-proper to match the other OSS'.

**Comment by nassosterz-ms** [comment]
Documentation fix should be live soon.
