### ISSUE TITLE
Suggestion: Rn repo to `PlayFabUnrealOSS`?

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/PlayFabMultiplayerUnreal#30]
Without OSS in the title, it gets quite confusing since it's so similar to all the other ones. This also matches what the README actually calls the repo.

> PlayFab Online Subsystem (OSS) Quickstart

Even keeping the _Multiplayer_ name in it gets confusing since the "core" SDK (or whatever you call it; has so many inconsistent names - the marketplace plugin) has Multiplayer API inside this, already.

**Comment by nassosterz-ms** [comment]
Closing this issue since it is duplicate of: https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/28
