### ISSUE TITLE
Critically missing examples/workflow docs (both online+inline)

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/PlayFabMultiplayerUnreal#31]
There's 0 direction I could find except [how to install the plugin](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart). Not even the inline docs have a single comment except the redundant name of the function.

![image](https://user-images.githubusercontent.com/8840024/216224513-edd2de93-6ef8-4eed-94f4-3e54fa82a53a.png)

## Where are the other OSS docs? 

1. Where/how do I init the SDK, if any?
2. Does this SDK use singletons, mostly, like the client sdk? Some sample API interactions.
3. Why would I call `OnlineIdentiyInterfacePlayFab::TriggerOnLoginCompleteDelegates` after already logged in? What does this actually trigger? 
4. Workflow? Best practices?
5. Matchmaking events?

I'm struggling to find anything past how to install the plugin.

**Comment by yuehanlin** [comment]
Thanks for your questions, and here are the answers to your question.

**1&2**. After adding below code (details please view [PlayFab Online Subsystem (OSS) Quickstart - PlayFab | Microsoft Learn](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart?source=recommendations))

```

[OnlineSubsystem]
DefaultPlatformService=PlayFab
```

UE OnlineSubsystemModule will use create online subsystem instance for PlayFab, therefore will start create ⁠[PlayFabSingleton](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFabModule.cpp#:~:text=ESPMode%3A%3AThreadSafe%3E(InstanceName)%3B-,if%20(PlayFabSingleton%2D%3EIsEnabled()),%7D,-else). At this point, SDK is initialized in⁠ [FOnlineSubsystemPlayFab::Init()](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp#:~:text=bool%20FOnlineSubsystemPlayFab%3A%3AInit()), where it'll initialize both Party and Multiplayer SDK with PlayFab TitleID (this titleID is defined inside your platform.ini file which is shown in [PlayFab Online Subsystem (OSS) Quickstart - PlayFab | Microsoft Learn](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart?source=recommendations)). During initialization, we'll ⁠[CreatePlayFabSocketSubsystem()](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp#:~:text=CreatePlayFabSocketSubsystem()) as main online subsystem. 

In this repo, we manage Party SDK use ⁠[Singleton](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp#:~:text=void%20FOnlineSubsystemPlayFab%3A%3ADoWork,PartyManager%3A%3AGetSingleton()%3B) structure, which handles the PartyStateChangeType get from ⁠[Party library](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/9ac0225e8fd2dd6ecd575ccd7243bbdbdfe6799e/Platforms/Windows/Include/PartyImpl.h#:~:text=PartyError%20PartyManager%3A%3AStartProcessingStateChanges,%7D). For Multiplayer, view 4&5.


**3**.This TriggerOnLoginCompleteDelegates was used for handling when login was unsuccessful for a user. Now, we are managing the login users using ⁠[UsersToAuth](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineIdentityInterfacePlayFab.cpp#:~:text=%7B-,if%20(NewStatus%20%3D%3D%20ELoginStatus%3A%3ALoggedIn),%7D,-%7D) .


**4&5**.Workflow of Multiplayer SDK: FOnlineSubsystemPlayFab::Init() initialize the MatchmakingInterface and PlayFabLobbyInterface . These 2 interfaces calling ⁠[Dowork()](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSessionInterfacePlayFab.cpp#:~:text=OSSPlayFab%2D%3EGetPlayFabLobbyInterface()%2D%3EDoWork,OSSPlayFab%2D%3EGetMatchmakingInterface()%2D%3EDoWork()%3B) which will handle the states changes from PFMultiplayerStartProcessingMatchmakingStateChanges and PFMultiplayerStartProcessingLobbyStateChanges (view Platforms/<Platform>/Include/PFMatchmaking.h and PFLobby.h to see these 2 functions).

**Comment by dylanh724** [comment]
> Thanks for your questions, and here are the answers to your question.
> 
> **1&2**. After adding below code (details please view [PlayFab Online Subsystem (OSS) Quickstart - PlayFab | Microsoft Learn](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart?source=recommendations))
> 
> ```
> 
> [OnlineSubsystem]
> DefaultPlatformService=PlayFab
> ```
> 
> UE OnlineSubsystemModule will use create online subsystem instance for PlayFab, therefore will start create ⁠[PlayFabSingleton](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFabModule.cpp#:~:text=ESPMode%3A%3AThreadSafe%3E(InstanceName)%3B-,if%20(PlayFabSingleton%2D%3EIsEnabled()),%7D,-else). At this point, SDK is initialized in⁠ [FOnlineSubsystemPlayFab::Init()](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp#:~:text=bool%20FOnlineSubsystemPlayFab%3A%3AInit()), where it'll initialize both Party and Multiplayer SDK with PlayFab TitleID (this titleID is defined inside your platform.ini file which is shown in [PlayFab Online Subsystem (OSS) Quickstart - PlayFab | Microsoft Learn](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart?source=recommendations)). During initialization, we'll ⁠[CreatePlayFabSocketSubsystem()](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp#:~:text=CreatePlayFabSocketSubsystem()) as main online subsystem. 
> 
> In this repo, we manage Party SDK use ⁠[Singleton](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp#:~:text=void%20FOnlineSubsystemPlayFab%3A%3ADoWork,PartyManager%3A%3AGetSingleton()%3B) structure, which handles the PartyStateChangeType get from ⁠[Party library](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/9ac0225e8fd2dd6ecd575ccd7243bbdbdfe6799e/Platforms/Windows/Include/PartyImpl.h#:~:text=PartyError%20PartyManager%3A%3AStartProcessingStateChanges,%7D). For Multiplayer, view 4&5.
> 
> **3**.This TriggerOnLoginCompleteDelegates was used for handling when login was unsuccessful for a user. Now, we are managing the login users using ⁠[UsersToAuth](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineIdentityInterfacePlayFab.cpp#:~:text=%7B-,if%20(NewStatus%20%3D%3D%20ELoginStatus%3A%3ALoggedIn),%7D,-%7D) .
> 
> **4&5**.Workflow of Multiplayer SDK: FOnlineSubsystemPlayFab::Init() initialize the MatchmakingInterface and PlayFabLobbyInterface . These 2 interfaces calling ⁠[Dowork()](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSessionInterfacePlayFab.cpp#:~:text=OSSPlayFab%2D%3EGetPlayFabLobbyInterface()%2D%3EDoWork,OSSPlayFab%2D%3EGetMatchmakingInterface()%2D%3EDoWork()%3B) which will handle the states changes from PFMultiplayerStartProcessingMatchmakingStateChanges and PFMultiplayerStartProcessingLobbyStateChanges (view Platforms//Include/PFMatchmaking.h and PFLobby.h to see these 2 functions).

This is great! 

Any chance you can toss this [to the Unreal OSS quickstart doc](https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart)? Possibly even more details, if possible -- it's really only you that knows this. If we pop in the PF discord or forum, no PF staff seems to know _anything_ about this SDK. Only you folks can help others.

The current quickstart only shows how to set it up and is missing best practices, workflow, entry points, high level overviews, etc. 

One thing that is desperately missing that I forgot to ask is OSS:PF vocab maps. 
**For example**, your OSS ResourceId isn't found in the PF API documentation. What this _actually_ is called in PF is MatchId. No one could ever possibly know this unless you meta search beyond the official docs, buried somewhere in Google.

**Comment by yuehanlin** [comment]
Thanks for your feedback. We've filed a bug to update the document to include your suggestions.

**Comment by dylanh724** [comment]
> FOnlineSubsystemPlayFab::Init()

Hey just a quick follow-up question:

![image](https://user-images.githubusercontent.com/8840024/224228523-bd0bce1a-af32-4bcf-85ed-92dc185e1c2e.png)

What is the default for `ReplicationDriverClassName`? Can I just comment it out?

**Comment by yuehanlin** [comment]
It's likely to be found at MyGame/Config/DefaultEngine.ini file. Find [/Script/OnlineSubsystemUtils.IpNetDriver] section or search ReplicationDriverClassName, and the value should looks like:
`ReplicationDriverClassName="/Script/MyGame.MyReplicationGraph"`

**Comment by dylanh724** [comment]
> It's likely to be found at MyGame/Config/DefaultEngine.ini file. Find [/Script/OnlineSubsystemUtils.IpNetDriver] section or search ReplicationDriverClassName, and the value should looks like: `ReplicationDriverClassName="/Script/MyGame.MyReplicationGraph"`

Perfect, thanks!!

**Comment by yuehanlin** [comment]
Workflow of OSS was added into the new release document https://learn.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unreal-engine-oss-quickstart#workflow-of-pf-oss, so I'll close this issue.
