### ISSUE TITLE
PF OSS not creating a socketsubsystem if marketplace plugin installed?

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/PlayFabMultiplayerUnreal#33]
Unless you just so happen to wander across a blue moon [in your Discord from non-staff on a very specific date from just another PF user from a 2022 post](https://discord.com/channels/684463257276121192/803421812352090112/1019486053268209704), absolutely no one would know that if you have the marketplace plugin, socketsubsystem isn't created.

How would anyone possibly know? Anytime someone has questions, PF staff vaguely redirects us to UE4's OSS docs; as if they used identical naming conventions, namespaces and transparently have strange init issues like the one mentioned above. Even your latest n greatest matchmaking docs start you with the Multiplayer SDK then 1/2 way tell you to use the OSS for event callbacks (rather than polling); in theory, _everyone_ should eventually encounter this bug.

Related to many of the other issues posted here, 

[ https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/32 , https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/30 , https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/31 , https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/28 , https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/27 ,  ]

it all funnels down to _**you have NO OSS docs**_. No one -- not even staff -- seems to know how to use the PF OSS alongside the "core sdk"  multiplayer::matchmaking api. This isn't a 1:1 interface implementation; it's wildly different. 

* How to properly init the SDK? Your guide says we need to call a special Initialize call and another func to set the entity key, but there's no similar call that stands out. We have no init instructions.
* When OnMatchmakingComplete triggers and includes `FName Name`, how do you expect your users what the heck this translates to in PF vocab? MatchmakingTicketId? MatchId? We have no PF:OSS map for terminology. Eg, OSS Session == PF Matchmaking. OSS Session `Name` == `PF_??`
* When we *only* want to add _OnMatchmaking_ delegates by following your multiplayer matchmaking tutorial, there's no clarifications about what prereq's we may need for the OSS. Seems like I can't *only* add to OnMatchmakingComplete, but need to setup a local session? Maybe? And again -- their terminology is different, so even if this is required, I don't know what to call and with what args from PF due to ambiguity and [again] lacking docs.

There's no inline docs, no online docs for this. Who is responsible for technical docs for the OSS so that I may directly contact them? No one seems to take responsibility.

___

This could be related: https://github.com/PlayFab/PlayFabMultiplayerUnreal/issues/22 -- however, posted months ago with minimal contributor activity.

**Comment by yuehanlin** [comment]
Thank you for reporting that.

This is the temporary solution to resolve it in https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/main/Source/Private/OnlineSubsystemPlayFab.cpp.
Change line 107 from`TSharedPtr<IPlugin> SocketsPlugin = IPluginManager::Get().FindPlugin(TEXT("PlayFab"));` 
to `TSharedPtr<IPlugin> SocketsPlugin = IPluginManager::Get().FindPlugin(TEXT("PlayFabParty"));` .

We've filed a bug, and will update the new release as soon as possible.

**Comment by yuehanlin** [comment]
Solution updated in the latest release 2.2.6, close this issue.
