### ISSUE TITLE
Error C4703 on Xbox

### ISSUE THREAD

**Issue by scovertb** [PlayFab/PlayFabMultiplayerUnreal#44]
When compiling for Xbox Series X with the Shipping configuration, [PlayFabHelpers.cpp](https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/d92f7103e256b24ea1d28f86f480cfecdb91cb8c/Source/Private/PlayFabHelpers.cpp) produces two C4703 errors on lines 362 and 424 due to uninitialized pointers. I was able to resolve this locally by initializing the `JsonDataObject` pointers to `nullptr` on lines 355 and 417.

**Comment by yuehanlin** [comment]
Thank you for reporting the issue! We will incorporate the fix in a future release.

**Comment by yuehanlin** [comment]
We recently released new OSS version with the fix, so I'll close this issue.
