### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Grapeman-zx** [PlayFab/PlayFabMultiplayerUnreal#63]
My Engine Version is 5.2。Ffrom UnrealEngine Git Clone.
![image](https://github.com/PlayFab/PlayFabMultiplayerUnreal/assets/24790441/431b4d4a-c9a3-4f4a-8acf-9cd61c43ddd6)

**Comment by yuehanlin** [comment]
Could you please let me know which OnlineSubsystemPlayFab version you're using? Could you check if PlayFabMultiplayerWin.lib is located in the path where the error is reported?

**Comment by yuehanlin** [comment]
I am going to close this issue since there is no additional information. However, please feel free to reopen it if you have any follow-up questions or require further assistance!
