### ISSUE TITLE
Windows libs throw "LNK1107: invalid or corrupt file: cannot read at 0x82" error

### ISSUE THREAD

**Issue by whitlai** [PlayFab/PlayFabMultiplayerUnreal#70]
I'm trying to integrate the PlayFab OSS plugin following the steps online. After unpacking the files into the Plugins\Online folder of my engine, when building I get the following error for the 2 libs in the Platforms\Windows\Lib folder:

PartyWin.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x82

**Comment by nassosterz-ms** [comment]
Hello,

Apologies you are facing this issue. May I ask, have you cloned our repository with git using LFS?

**Comment by whitlai** [comment]
I downloaded the zip! I just tried cloning the repo and it did work. Not sure why it was different with the zip. Thank you!

**Comment by nassosterz-ms** [comment]
Sounds good, closing!
